name: appback_sdk
description: Library to implement AppBack services in Flutter applications.
version: 0.0.1+1
homepage: https://github.com/appback-io/appback-flutter

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  http: ^0.12.0+4
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.2.5
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.appback.app_back
        pluginClass: AppBackPlugin
      ios:
        pluginClass: AppBackPlugin