name: app_back
description: The official Flutter library for Appback.
version: 0.0.1
author: Nicolás David Muñoz Cuervo
homepage: https://github.com/ndmunoz/app_back

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: ^0.12.0+3
  get_it: ^3.1.0
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.2.5
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter